---
# tasks file for ansible-bootstrap

# moved to mrlesmithjr.users
#- include: users.yml
#  tags:
#    - bootstrap_users

- include: debian.yml
  when: ansible_os_family == "Debian"

- include: debian_security.yml
  when: ansible_os_family == "Debian"

- include: centos.yml
  when: ansible_os_family == "RedHat"

- include: centos_security.yml
  when: ansible_os_family == "RedHat"

- include: lockdown.yml
